#!/bin/bash

RTYPE=$1
RNAME=$2
IP=$3
ZONE=$4

while getoptions 'o:' OPTIONS; do
	case "$OPTIONS" in
		o) if [$RTYPE == A ]
			then
				echo "Writing record"
				echo ";Name Server Records"		 >>/etc/bind/db.$ZONE
				echo "${NAME}	IN	A	${IP}"    >>/etc/bind/db.$ZONE
				echo "Yes, $RTYPE $NAME $ZONE"

		   elif [$RTYPE == MX ]
			then
				echo "Creating record"
				echo ";Name Server Records"		 >>/etc/bind/db.$ZONE
				echo "${NAME}   IN      A       ${IP}"    >>/etc/bind/db.$ZONE
				echo "Yes, $RTYPE $NAME $ZONE"

		   elif [$RTYPE == CNAME ]
			then
				echo "Creating CNAME record"
				echo ";Name Server CNAME"		>>/etc/bind/db.$ZONE
				echo "${NAME}   IN      CNAME       ${IP}"    >>/etc/bind/db.$ZONE
				echo "Yes, $RTYPE $NAME $ZONE"
		   fi
	esac
done
