#!/bin/bash

cat >> /etc/apache2/sites-available/$1.conf << EOL
	<VirtualHost *:80>
		ServerName $1
		ServerAlias $1
		DocmentRoot /var/www/html/www.$1
		ErrorLog ${APACHE_LOG_DIR}/$1-error.log
		CustomLog ${APACHE_LOG_DIR}/$1-acces.log combined
	</VirtualHost>
EOL

mkdir /var/www/html/www.$1
echo "Welcome $1" >> /var/www/html/index.html
echo "Welcome www.$1" >> /var/www/html/www.$1/index.html

a2ensite $1
systemctl reload apache2
systemctl restart apache2
